### ISSUE TITLE
would you be up for working together to make a typescript/javascript NPM library to standardize USJ?

### ISSUE THREAD

**Issue by alilland** [mvh-solutions/nice-usfm-json#11]
been poking around with this library the last two days, i'm building something with USX and hate it, and was looking for something to parse as JSON. your github repo was suggested. Would you be up for starting an NPM library? I took your code and already ported it over typescript privately

**Comment by mvahowe** [comment]
Hi! Let's talk! Personally, I think that format adoption depends a lot on suitable libraries. Within the people in the conversation we already have several libraries that produce JSON that is used in production in various places. So, personally, I'd be inclined to start there, rather than doing something from scratch. But I'm open to being convinced otherwise.

**Comment by joelthe1** [comment]
Hi @alilland, thanks for asking! As Mark suggested, let us know if you'd be interested to jump on a call and find ways to collaborate.

**Comment by alilland** [comment]
sure, would love to 😊, come February i'll be working on a project full time that I'll be looking to leverage USJ with - the one here worked fine and seemed complete enough to fit my anticipated needs, i'm open to whatever so long as its has official support

**Comment by joelthe1** [comment]
Great! I couldn't find your email address on your GitHub profile. But it should be visible on mine. Could you reach out over email and I'll try to find a time for us to talk.
