### ISSUE TITLE
Lighter JSON

### ISSUE THREAD

**Issue by kavitharaju** [mvh-solutions/nice-usfm-json#3]
The more complex the markups in USFM needs to be, the size of the corresponding JSON will also increase drastically. But as we define the schema, keeping it as light as possible could be a consideration.

Compared the sizes of SOFRIA.json and the JSON schema we put forth before the committee. Used the eBible_engBBE_2020-04-17_RUT obtained from [https://diegesis.bible](https://diegesis.bible/entry/details/eBible/engBBE/2020-04-17)
 
- Original USFM file size = 66.3 kB
- SOFRIA json = **622.7 kB**
- USFM-Grammar JSON = **465.3 kB**

Both the JSON's indentation was kept as 1 space for comparison.
Even after using bare strings and eliminating the closing marker information for light weightedness, SOFRIA seems quite bulky. I think the use case specific metadata like `graft`, `sequence`, `block`, `mark`, etc that are being added on top of the USFM data could be the culprit here.

When there is a genuine need to club together components in USFM, we could use `wrapper` and also `content` for realizing nesting of components. These would be self explanatory to a user. But we could avoid too many different terminologies and concepts being introduced into a general purpose model.

**Comment by mvahowe** [comment]
Thanks for running the tests!

There's a 33% difference. Personally, I don't think that's a big deal compared with the 10x bloat of moving from USFM to JSON, period.

The real memory I think we should care about is in-memory, which is typically 10-20x the serialized size, and objects are particularly expensive because of all the pointers.

Extra nesting means one more character per line just because of indentation. What happens if you don't prettyprint, ie all the JSON is one one line? That would be a more realistic production scenario.

mark actually saves memory because it replace and open/close milestone pair. What does a ts milestone look like in your JSON?

Try removing all the usfm namespaces, ie s/usfm://g

**Comment by mvahowe** [comment]
The other thing to say is that Proskomma enums all text, so the length of keys and indeed the number of keys (within reason) makes almost no difference.

**Comment by kavitharaju** [comment]
You are right about extra nesting adding newlines and indentation. Without them the sizes are as follows
- Original USFM file size = 66.3 kB
- SOFRIA json = 248.3 kB
- USFM-Grammar JSON = 218.8 kB

There is a drastic reduction in SOFRIA's size. I wonder if that is an indicator of level of nesting complexity.

For our task at hand the serialized format is the focus, right? We need to worry not only about in-memory space and processing but also about how well it would work as a data representation and exchange medium. There lower size and readability are important too.

[This](https://github.com/kavitharaju/usfm-grammar/blob/yet-another-json/docs/JSON_refactor.md#16-milestones) is how we represent milestones. We don't wrap milestone contents as of now, but just represent the markers' presence.

**Comment by mvahowe** [comment]
We're down to a 15% difference. Now if we remove the USFM namespacing of all tags?

`perl -pi -e 's/usfm://g' file.json`

ought to do it.
